services:
  - type: web
    name: agri-fraud-detection
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-hin tesseract-ocr-ben
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9